[tool.poetry]
name = "ability-evaluate"
version = "0.1.0"
description = ""
authors = ["FrozenString <964413011@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
py-irt = "^0.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
